import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Course = {
    CourseID: Generated<number>;
    CR_CourseCode: string;
    CR_Name: string;
    CR_Description: string | null;
    CR_DataStatus: number;
    CR_CreateTime: Timestamp;
    CR_CreateUser: string;
    CR_ModifyTime: Timestamp;
    CR_ModifyUser: string;
    CR_DeletedTime: Timestamp | null;
    CR_DeletedUser: string | null;
    CR_Version: number | null;
    CR_TrainingDetail: string | null;
    CR_NonTrainingDetail: string | null;
    CourseCategoryID: number | null;
    CR_SapCourseCode: string;
    CR_SourceType: string;
    CR_AdhocType: number | null;
    CR_CourseDataCreateDate: Timestamp | null;
    CR_CourseDataCreateUser: string;
    CR_CourseDataModifyDate: Timestamp | null;
    CR_CourseDataModifyUser: string;
};
export type CourseCategory = {
    CourseCategoryID: Generated<number>;
    CC_Code: string;
    CC_Name: string;
    CC_Description: string | null;
    CC_DataStatus: number;
    CC_CreateTime: Timestamp;
    CC_CreateUser: string;
    CC_ModifyTime: Timestamp;
    CC_ModifyUser: string;
    CC_DeletedTime: Timestamp | null;
    CC_DeletedUser: string | null;
    CC_Version: number | null;
    CC_TrainingDetail: string | null;
    CC_NonTrainingDetail: string | null;
};
export type CourseClass = {
    CourseClassID: Generated<number>;
    CRC_ClassCode: string | null;
    CRC_Name: string;
    CRC_Description: string | null;
    CRC_DataStatus: number;
    CRC_CreateTime: Timestamp;
    CRC_CreateUser: string;
    CRC_ModifyTime: Timestamp;
    CRC_ModifyUser: string;
    CRC_DeletedTime: Timestamp | null;
    CRC_DeletedUser: string | null;
    CRC_Version: number | null;
    CRC_SapClassCode: string;
    CRC_ClassDay: number | null;
    CRC_ClassBeginDate: Timestamp | null;
    CRC_ClassEndDate: Timestamp | null;
    CRC_ClassDataCreateDate: Timestamp | null;
    CRC_ClassDataCreateUser: string;
    CRC_ClassDataModifyDate: Timestamp | null;
    CRC_ClassDataModifyUser: string;
    CRC_TraningLocationID: number | null;
    CRC_TrainingLocationCode: string;
    CRC_TrainingLocationName: string;
    CRC_TrainingLocationFlag: number | null;
    CRC_TrainingPlace: string | null;
};
export type Curriculum = {
    CurriculumID: Generated<number>;
    CL_Code: string;
    CL_Name: string;
    CL_Description: string | null;
    CL_DataStatus: number;
    CL_CreateTime: Timestamp;
    CL_CreateUser: string;
    CL_ModifyTime: Timestamp;
    CL_ModifyUser: string;
    CL_DeletedTime: Timestamp | null;
    CL_DeletedUser: string | null;
    CL_Version: number | null;
};
export type CurriculumCourse = {
    CLC_DataStatus: number;
    CLC_CreateTime: Timestamp;
    CLC_CreateUser: string;
    CLC_ModifyTime: Timestamp;
    CLC_ModifyUser: string;
    CurriculumID: number;
    CourseID: number;
    CLC_DeletedTime: Timestamp | null;
    CLC_DeletedUser: string | null;
    CLC_Version: number | null;
};
export type Organization = {
    OrganizationID: Generated<number>;
    ORG_ParentOrganizationID: number | null;
    ORG_Code: string | null;
    ORG_Type: Generated<number>;
    ORG_EShortName: string | null;
    ORG_TShortName: string | null;
    ORG_ELongName: string | null;
    ORG_TLongName: string | null;
    ORG_Description: string | null;
    ORG_DataStatus: Generated<number>;
    ORG_CreateTime: Timestamp;
    ORG_CreateUser: string;
    ORG_ModifyTime: Timestamp;
    ORG_ModifyUser: string;
    ORG_ERPCode: string | null;
    ORG_OrgIDLevel01: number | null;
    ORG_OrgIDLevel02: number | null;
    ORG_OrgIDLevel03: number | null;
    ORG_OrgIDLevel04: number | null;
    ORG_OrgIDLevel05: number | null;
    ORG_OrgIDLevel06: number | null;
    ORG_OrgIDLevel07: number | null;
    ORG_OrgIDLevel08: number | null;
    ORG_OrgIDLevel09: number | null;
    ORG_DeletedTime: Timestamp | null;
    ORG_DeletedUser: string | null;
    ORG_OwnerGroupID: number | null;
    ORG_OwnerUserID: number | null;
    ORG_Version: number | null;
    ORG_Level: number | null;
    ORG_BossPersonID: number | null;
    ORG_ENamePath: string | null;
    ORG_TNamePath: string | null;
    ORG_PhoneNumber: string;
    ORG_EMail: string;
    ORG_WebSite: string;
    ORG_SyncBeginTime: Timestamp | null;
    ORG_SyncEndTime: Timestamp | null;
    ORG_SyncStatus: number | null;
    ORG_LastSyncStatus: number | null;
    ORG_SyncUser: string | null;
    ORG_SyncVersion: number | null;
    ORG_TNameReversePath: string | null;
};
export type Person = {
    PersonID: Generated<number>;
    PS_BossPersonID: number;
    PS_OrganizationID: number | null;
    PS_Code: string | null;
    PS_Type: Generated<number>;
    PS_TPrefixName: string | null;
    PS_TName: string | null;
    PS_TLastName: string | null;
    PS_TAddress: string | null;
    PS_EPrefixName: string | null;
    PS_EName: string | null;
    PS_ELastName: string | null;
    PS_EAddress: string | null;
    PS_IDCode: string | null;
    PS_Gender: number | null;
    PS_BirthDay: Timestamp | null;
    PS_MaritalStatus: number | null;
    PS_PostCode: string | null;
    PS_EMailAddress: string | null;
    PS_EMailAddress2ND: string | null;
    PS_PersonStatus: Generated<number | null>;
    PS_CreateTime: Timestamp;
    PS_CreateUser: string;
    PS_ModifyTime: Timestamp;
    PS_ModifyUser: string;
    PS_Level: number | null;
    PS_AdmissionDate: Timestamp | null;
    PS_BloodGroup: string | null;
    PS_InternalPhoneNumber: string | null;
    PS_PhoneNumber: string | null;
    PS_DataStatus: number;
    PS_LoginPassword: string | null;
    PS_LoginName: string | null;
    PS_DeletedTime: Timestamp | null;
    PS_DeletedUser: string | null;
    PS_Version: number | null;
    PS_Nationality: string | null;
    PS_Religion: string | null;
    PS_ChildStatus: number | null;
    PS_NumberOfChild: number | null;
    PS_SyncStatus: number | null;
    PS_SyncVersion: number | null;
    PS_SyncBeginTime: Timestamp;
    PS_SyncEndTime: Timestamp;
    PS_LastSyncStatus: number | null;
    PS_EmployeeStatus: number | null;
    PS_WorkBeginDate: Timestamp;
    PS_WorkEndDate: Timestamp | null;
    PS_PersonAge: number | null;
    PS_TTitleName: string | null;
    PS_EFullName: string | null;
    PS_TaxpayerCode: string;
    PS_NOFChild: number | null;
    PS_Weight: number | null;
    PS_Height: number | null;
    PS_RegisterAddress: string | null;
    PS_HomeAddress: string | null;
    PS_MobilePhoneNumber: string | null;
    PS_RetirementDate: Timestamp | null;
    PS_EmploymentDate: Timestamp | null;
    PS_EmploymentStatus: number | null;
    PS_TerminationDate: Timestamp | null;
    PS_TerminationType: number | null;
    PS_ContractTerminateDate: Timestamp | null;
};
export type PersonAttribute = {
    PA_CreateTime: Timestamp;
    PA_CreateUser: string;
    PA_ModifyTime: Timestamp;
    PA_ModifyUser: string;
    PA_DataStatus: number;
    PA_DeletedTime: Timestamp | null;
    PA_DeletedUser: string | null;
    PA_Version: number | null;
    PersonAttributeID: number;
    PA_PersonLevel: number | null;
    PA_PersonCode: string;
    PA_PersonName: string;
    PA_PersonOrganizationCode: string;
    PA_PersonOrganizationName: string;
    PA_PersonBossStatus: string | null;
    PA_PersonProjectMemberStatus: string | null;
    PA_PersonBossRepresentStatus: string | null;
    PA_SyncBeginTime: Timestamp | null;
    PA_SyncUser: string | null;
    PA_SyncVersion: number | null;
    PA_PersonWorkAttendDate: Timestamp | null;
    PA_DataValidYear: number | null;
    PA_DataValidBeginDate: Timestamp | null;
    PA_DataValidEndDate: Timestamp | null;
    PA_SyncEndTime: Timestamp | null;
    PA_SyncStatus: number | null;
    PA_LastSyncStatus: number | null;
};
export type PersonAttributePotential = {
    PAP_CreateTime: Timestamp;
    PAP_CreateUser: string;
    PAP_ModifyTime: Timestamp;
    PAP_ModifyUser: string;
    PAP_DataStatus: number;
    PAP_DeletedTime: Timestamp | null;
    PAP_DeletedUser: string | null;
    PAP_Version: number | null;
    PersonAttributePotentialID: number;
    PAP_PersonCode: string;
    PAP_PersonName: string;
    PAP_PersonOrganizationCode: string;
    PAP_PersonOrganizationName: string;
    PAP_PersonPotentialType: string | null;
    PAP_PersonPotentialInYear: string | null;
    PAP_SyncBeginTime: Timestamp | null;
    PAP_SyncUser: string | null;
    PAP_SyncVersion: number | null;
    PAP_DataValidYear: number | null;
    PAP_DataValidBeginDate: Timestamp | null;
    PAP_DataValidEndDate: Timestamp | null;
    PAP_SyncEndTime: Timestamp | null;
    PAP_SyncStatus: number | null;
    PAP_LastSyncStatus: number | null;
};
export type PersonAttributeSjf = {
    PAS_CreateTime: Timestamp;
    PAS_CreateUser: string;
    PAS_ModifyTime: Timestamp;
    PAS_ModifyUser: string;
    PAS_DataStatus: number;
    PAS_DeletedTime: Timestamp | null;
    PAS_DeletedUser: string | null;
    PAS_Version: number | null;
    PersonAttributeSjfID: number;
    PAS_PersonCode: string;
    PAS_PersonName: string;
    PAS_PersonOrganizationCode: string;
    PAS_PersonOrganizationName: string;
    PAS_PersonSJFCode: string | null;
    PAS_SyncBeginTime: Timestamp | null;
    PAS_SyncUser: string | null;
    PAS_SyncVersion: number | null;
    PAS_DataValidYear: number | null;
    PAS_DataValidBeginDate: Timestamp | null;
    PAS_DataValidEndDate: Timestamp | null;
    PAS_SyncEndTime: Timestamp | null;
    PAS_SyncStatus: number | null;
    PAS_LastSyncStatus: number | null;
};
export type PersonAttributeSjfDetail = {
    PASD_CreateTime: Timestamp;
    PASD_CreateUser: string;
    PASD_ModifyTime: Timestamp;
    PASD_ModifyUser: string;
    PASD_DataStatus: number;
    PASD_DeletedTime: Timestamp | null;
    PASD_DeletedUser: string | null;
    PASD_Version: number | null;
    PersonAttributeSjfDetailID: number;
    PASD_PersonCode: string;
    PASD_PersonSJFCode: string | null;
    PASD_SyncBeginTime: Timestamp | null;
    PASD_SyncUser: string | null;
    PASD_SyncVersion: number | null;
    PASD_SyncEndTime: Timestamp | null;
    PASD_SyncStatus: number | null;
    PASD_LastSyncStatus: number | null;
    PersonAttributeSjfID: number | null;
    PASD_PersonCompetencyCode: string | null;
    PASD_PersonCompetencyPLStandardMark: string | null;
    PASD_PersonCompetencyType: string | null;
};
export type PersonElsTrainingHistory = {
    PETH_CreateTime: Timestamp;
    PETH_CreateUser: string;
    PETH_ModifyTime: Timestamp;
    PETH_ModifyUser: string;
    PETH_DataStatus: number;
    PETH_DeletedTime: Timestamp | null;
    PETH_DeletedUser: string | null;
    PETH_Version: number | null;
    PersonTrainingHistoryID: number;
    PETH_CourseCode: number;
    PETH_CourseClassID: number;
    PETH_SapCourseCode: string | null;
    PETH_SapClassCode: string;
    PETH_PersonCode: string;
    PETH_PersonName: string;
    PETH_PersonLevel5OrgAliasName: string;
    PETH_CourseCategoryName: string;
    PETH_EnrollmentType: string | null;
    PETH_PositonAliasName: string | null;
    PETH_PositionName: string | null;
    PETH_PersonLevel: string | null;
    PETH_PersonLevel1OrgAliasName: string;
    PETH_PersonLevel2OrgAliasName: string;
    PETH_PersonLevel3OrgAliseName: string;
    PETH_PersonLevel4OrgAliasName: string;
    PETH_LearningProcessStatus: string;
    PETH_LearningCompletedDate: string;
    PETH_LearningProgressPercent: string;
    PETH_LearningEnrollmentDate: string;
    PETH_LearningStartDate: string;
    PETH_LearningConditionPassPercent: string;
    PETH_LearningPassPercent: string;
    PETH_EnrollToCompletedTime: string;
    PETH_StartToCompletedTime: string;
    PETH_LearningInProgressFlag: string;
    PETH_LearningNotStartFlag: string;
};
export type PersonTrainingHistory = {
    PTH_CreateTime: Timestamp;
    PTH_CreateUser: string;
    PTH_ModifyTime: Timestamp;
    PTH_ModifyUser: string;
    PTH_DataStatus: number;
    PTH_DeletedTime: Timestamp | null;
    PTH_DeletedUser: string | null;
    PTH_Version: number | null;
    PersonTrainingHistoryID: number;
    CourseID: number | null;
    CourseClassID: number | null;
    PTH_SapCourseCode: string;
    PTH_SapClassCode: string;
    PTH_PersonCode: string;
    PTH_PersonName: string;
};
export type TrainingLocation = {
    TL_CreateTime: Timestamp;
    TL_CreateUser: string;
    TL_ModifyTime: Timestamp;
    TL_ModifyUser: string;
    TL_DataStatus: number;
    TL_DeletedTime: Timestamp | null;
    TL_DeletedUser: string | null;
    TL_Version: number | null;
    TL_SyncBeginTime: Timestamp | null;
    TL_SyncUser: string | null;
    TL_SyncVersion: number | null;
    TraningLocationID: Generated<number>;
    TL_SyncEndTime: Timestamp | null;
    TL_SyncStatus: number | null;
    TL_LastSyncStatus: number | null;
    TL_Code: string;
    TL_Name: string;
    TraningLocationMainGroupID: number | null;
    TraningLocationSubGroupID: number | null;
    TL_Description: string | null;
    TL_AliasName: string;
};
export type TrainingLocationMainGroup = {
    TLMG_CreateTime: Timestamp;
    TLMG_CreateUser: string;
    TLMG_ModifyTime: Timestamp;
    TLMG_ModifyUser: string;
    TLMG_DataStatus: number;
    TLMG_DeletedTime: Timestamp | null;
    TLMG_DeletedUser: string | null;
    TLMG_Version: number | null;
    TLMG_SyncBeginTime: Timestamp | null;
    TLMG_SyncUser: string | null;
    TLMG_SyncVersion: number | null;
    TraningLocationMainGroupID: Generated<number>;
    TLMG_SyncEndTime: Timestamp | null;
    TLMG_SyncStatus: number | null;
    TLMG_LastSyncStatus: number | null;
    TLMG_Code: string;
    TLMG_Name: string;
    TLMG_Description: string | null;
};
export type TrainingLocationSubGroup = {
    TLSG_CreateTime: Timestamp;
    TLSG_CreateUser: string;
    TLSG_ModifyTime: Timestamp;
    TLSG_ModifyUser: string;
    TLSG_DataStatus: number;
    TLSG_DeletedTime: Timestamp | null;
    TLSG_DeletedUser: string | null;
    TLSG_Version: number | null;
    TLSG_SyncBeginTime: Timestamp | null;
    TLSG_SyncUser: string | null;
    TLSG_SyncVersion: number | null;
    TraningLocationSubGroupID: Generated<number>;
    TLSG_SyncEndTime: Timestamp | null;
    TLSG_SyncStatus: number | null;
    TLSG_LastSyncStatus: number | null;
    TLSG_TraningLocationMainGroupID: number | null;
    TLSG_Code: string;
    TLSG_Name: string;
    TLSG_Description: string | null;
};
export type TrainingRoadmap = {
    TrainingRoadmapID: Generated<number>;
    TR_Code: string;
    TR_Name: string;
    TR_Description: string | null;
    TR_DataStatus: number;
    TR_CreateTime: Timestamp;
    TR_CreateUser: string;
    TR_ModifyTime: Timestamp;
    TR_ModifyUser: string;
    TR_DeletedTime: Timestamp | null;
    TR_DeletedUser: string | null;
    TR_Version: number | null;
    TR_TrmType: number | null;
    TR_BeginPublicDate: Timestamp | null;
    TR_EndPublicDate: Timestamp | null;
    TR_BeginTrmYear: number | null;
    TR_EndTrmYear: number | null;
};
export type TrainingRoadmapDevArea = {
    TRDA_Code: string;
    TRDA_Name: string;
    TRDA_Description: string | null;
    TRDA_DataStatus: number;
    TRDA_CreateTime: Timestamp;
    TRDA_CreateUser: string;
    TRDA_ModifyTime: Timestamp;
    TRDA_ModifyUser: string;
    TRDA_DeletedTime: Timestamp | null;
    TRDA_DeletedUser: string | null;
    TRDA_Version: number | null;
    TrainRoadMapDevAreaID: Generated<number>;
    ParentTrainRoadMapDevAreaID: number | null;
    TRDA_DevAreaLevel: number | null;
    TRDA_DevAreaType: number | null;
    TrainingRoadmapID: number | null;
    TRDA_CompetencyCode: string;
    TRDA_CompetencyName: string;
};
export type TrainingRoadmapDevAreaCourse = {
    TRDAC_Code: string;
    TRDAC_Name: string;
    TRDAC_Description: string | null;
    TRDAC_DataStatus: number;
    TRDAC_CreateTime: Timestamp;
    TRDAC_CreateUser: string;
    TRDAC_ModifyTime: Timestamp;
    TRDAC_ModifyUser: string;
    TRDAC_DeletedTime: Timestamp | null;
    TRDAC_DeletedUser: string | null;
    TRDAC_Version: number | null;
    TrainRoadMapDevAreaCourseID: Generated<number>;
    TrainRoadMapMainDevAreaID: number;
    TRDAC_TrainedValidYear: number | null;
    TRDAC_CompetencyBeginPLStandardMark: number | null;
    TRDAC_CompetencyEndPLStandardMark: number | null;
    TrainingRoadmapID: number;
    TRDAC_TrainingYear: number | null;
    TrainRoadMapSubDevAreaID: number;
    CourseID: number | null;
};
export type TrainingRoadmapDistributeRule = {
    TrainingRoadmapDistributeRuleID: Generated<number>;
    TRDR_Description: string | null;
    TRDR_DataStatus: number;
    TRDR_CreateTime: Timestamp;
    TRDR_CreateUser: string;
    TRDR_ModifyTime: Timestamp;
    TRDR_ModifyUser: string;
    TRDR_DeletedTime: Timestamp | null;
    TRDR_DeletedUser: string | null;
    TRDR_Version: number | null;
    TRDR_TrmType: number | null;
    TrainingRoadmapID: number | null;
    TRDR_BeginPersonLevel: number | null;
    TRDR_EndPersonLevel: number | null;
    TRDR_BossStatus: number | null;
    TRDR_NewEmployeeBeginDate: Timestamp | null;
    TRDR_NewEmployeeEndDate: Timestamp | null;
    TRDR_SJFCode: string;
    TRDR_Order: number | null;
    TRDR_PotentialCode: string;
    TRDR_PotentialInYear: number | null;
    TRDR_ProjectMemberStatus: number | null;
    TRDR_BossRepresentStatus: number | null;
    TRDR_Name: string;
};
export type TRMPersonJourney = {
    TRMPersonJourneyID: Generated<number>;
    PJ_DataStatus: number;
    PJ_CreateTime: Timestamp;
    PJ_CreateUser: string;
    PJ_ModifyTime: Timestamp;
    PJ_ModifyUser: string;
    PJ_DeletedTime: Timestamp | null;
    PJ_DeletedUser: string | null;
    PJ_Version: number | null;
    PJ_ProcessStatus: number | null;
    PJ_AssignTime: Timestamp | null;
    PJ_SuccessTime: Timestamp | null;
    TrainingRoadmapID: number | null;
    PersonID: number | null;
    PJ_AssignStatus: number | null;
    PJ_CancelTime: Timestamp;
    PJ_CancelUser: string;
    TrainingRoadmapDistributeRuleID: number | null;
    PJ_ValidateYear: number | null;
    PJ_ValidateRound: number | null;
    PJ_AssignUser: string;
    PJ_SuccessUser: string;
};
export type TRMPersonJourneyDetail = {
    TRMPersonJourneyDetailID: Generated<number>;
    PJD_DataStatus: number;
    PJD_CreateTime: Timestamp;
    PJD_CreateUser: string;
    PJD_ModifyTime: Timestamp;
    PJD_ModifyUser: string;
    PJD_DeletedTime: Timestamp | null;
    PJD_DeletedUser: string | null;
    PJD_Version: number | null;
    PJD_ProcessStatus: number | null;
    PJD_AssignTime: Timestamp | null;
    PJD_SuccessTime: Timestamp | null;
    TrainRoadMapDevAreaCourseID: number | null;
    TrainRoadMapMainDevAreaID: number | null;
    TrainingRoadmapID: number | null;
    PJD_AssignStatus: number | null;
    PJD_CancelTime: Timestamp;
    PJD_CancelUser: string;
    TRMPersonJourneyID: number | null;
    TrainRoadMapSubDevAreaID: number | null;
    CourseID: number | null;
    PJD_AssignUser: string;
    PJD_SuccessUser: string;
};
export type DB = {
    Course: Course;
    CourseCategory: CourseCategory;
    CourseClass: CourseClass;
    Curriculum: Curriculum;
    CurriculumCourse: CurriculumCourse;
    Organization: Organization;
    Person: Person;
    PersonAttribute: PersonAttribute;
    PersonAttributePotential: PersonAttributePotential;
    PersonAttributeSjf: PersonAttributeSjf;
    PersonAttributeSjfDetail: PersonAttributeSjfDetail;
    PersonElsTrainingHistory: PersonElsTrainingHistory;
    PersonTrainingHistory: PersonTrainingHistory;
    TrainingLocation: TrainingLocation;
    TrainingLocationMainGroup: TrainingLocationMainGroup;
    TrainingLocationSubGroup: TrainingLocationSubGroup;
    TrainingRoadmap: TrainingRoadmap;
    TrainingRoadmapDevArea: TrainingRoadmapDevArea;
    TrainingRoadmapDevAreaCourse: TrainingRoadmapDevAreaCourse;
    TrainingRoadmapDistributeRule: TrainingRoadmapDistributeRule;
    TRMPersonJourney: TRMPersonJourney;
    TRMPersonJourneyDetail: TRMPersonJourneyDetail;
};
